language: c
os: linux
compiler: gcc
sudo: required

services: 
    - docker

before_install:
    - printf "FROM misprit7/whistler-blackcomb:mcuxpressoide\nRUN mkdir -p /home/Whistler-Blackcomb\nCOPY ./* /home/Whistler-Blackcomb/" > Dockerfile
    - docker build -t new_image .
    - docker run new_image /bin/sh -c "ls; pwd; mcuxpressoide -nosplash --launcher.suppressErrors -application org.eclipse.cdt.managedbuilder.core.headlessBuild -data /home -cleanBuild Whistler-Blackcomb"

script: 
- cmake .
- cmake --build .
- ctest -j14 -C Debug -T test --output-on-failure
