language: c
os: linux
compiler: gcc
sudo: required

services: 
    - docker

before_install:
    - docker run misprit7/whistler-blackcomb:mcuxpressoide /bin/sh -c "ls; pwd; mcuxpressoide -nosplash --launcher.suppressErrors -application org.eclipse.cdt.managedbuilder.core.headlessBuild -data "/home" -cleanBuild Whistler-Blackcomb-v2"
    -

script: 
- cmake .
- cmake --build .
- ctest -j14 -C Debug -T test --output-on-failure
