/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */
#define SOPT5_UART1TXSRC_UART_TX 0x00u /*!<@brief UART 1 transmit data source select: UART1_TX pin */

/*! @name PORTC5 (number 110), LED_RGBBUILTIN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_BUILTIN_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_BUILTIN_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_BUILTIN_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_BUILTIN_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_BUILTIN_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTB16 (number 95), DEBUG_UART_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTB17 (number 96), DEBUG_UART_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTC3 (number 106), IMU_UART_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_IMU_UART_RX_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_IMU_UART_RX_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_IMU_UART_RX_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTC4 (number 109), IMU_UART_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_IMU_UART_TX_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_IMU_UART_TX_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_IMU_UART_TX_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
